#!/usr/bin/env bash
set -euo pipefail

# Reads workspace/topics/*.md (excluding _TEMPLATE.md), parses YAML frontmatter
# for chat_id + thread_id, and emits config/05-topics.local.json — a config
# fragment that registers each topic's body content as the per-topic systemPrompt
# in channels.telegram.groups.<chat_id>.topics.<thread_id>.systemPrompt.
#
# Source of truth: workspace/topics/<name>.md (markdown, editable).
# Derived: config/05-topics.local.json (gitignored, regenerated each run).
#
# Usage:
#   ./sync-topics.sh             # write derived config
#   ./sync-topics.sh --dry-run   # print to stdout, don't write
#
# After running: re-run merge-configs.sh and restart the gateway.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TOPICS_DIR="$SCRIPT_DIR/workspace/topics"
TARGET="$SCRIPT_DIR/config/05-topics.local.json"
DRY_RUN=0

[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=1

command -v jq >/dev/null 2>&1 || { echo "missing: jq (brew install jq)" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "missing: python3 (preinstalled on macOS)" >&2; exit 1; }

if [[ ! -d "$TOPICS_DIR" ]]; then
  echo "no topics directory at $TOPICS_DIR — nothing to sync" >&2
  exit 0
fi

# Use python to parse frontmatter + body cleanly. Bash is bad at YAML.
# Outputs a JSON object with channels.telegram.groups.<chat>.topics.<thread>.systemPrompt
merged="$(python3 - <<'PY' "$TOPICS_DIR"
import json, os, re, sys
topics_dir = sys.argv[1]
groups = {}
for fname in sorted(os.listdir(topics_dir)):
    if not fname.endswith(".md") or fname.startswith("_"):
        continue
    path = os.path.join(topics_dir, fname)
    with open(path, encoding="utf-8") as f:
        text = f.read()
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not m:
        print(f"skip {fname}: no frontmatter", file=sys.stderr)
        continue
    meta_block, body = m.group(1), m.group(2).strip()
    meta = {}
    for line in meta_block.splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            meta[k.strip()] = v.strip()
    chat_id = meta.get("chat_id")
    thread_id = meta.get("thread_id")
    if not chat_id or not thread_id or chat_id.startswith("REPLACE_") or thread_id.startswith("REPLACE_"):
        print(f"skip {fname}: missing or placeholder chat_id/thread_id", file=sys.stderr)
        continue
    groups.setdefault(chat_id, {}).setdefault("topics", {})[thread_id] = {
        "systemPrompt": body
    }

config = {
    "_comment": "Generated by sync-topics.sh from workspace/topics/*.md — do not edit by hand. Re-run sync-topics.sh after editing topic files.",
    "channels": {"telegram": {"groups": groups}}
} if groups else {"_comment": "No topics defined yet — drop a markdown file in workspace/topics/ (see _TEMPLATE.md)"}

print(json.dumps(config, indent=2))
PY
)"

if [[ $DRY_RUN -eq 1 ]]; then
  printf '%s\n' "$merged"
  exit 0
fi

mkdir -p "$(dirname "$TARGET")"
printf '%s\n' "$merged" > "$TARGET"
echo "wrote $TARGET"
echo
echo "next: ./merge-configs.sh && restart the openclaw gateway"
